cebaf_status.settings:
  type: config_object
  label: 'Cebaf Status Module Settings'
  mapping:
    caget_url:
      type: uri
      label: "Url of epics2web/caget service for fetching EPICS PV values"
    abcd_current_path:
      type: string
      label: "File path relative to public:// for Recent Beam Current graphic"
    pss_history_path:
      type: string
      label: "File path relative to public:// for PSS History graphic"
